apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: {{ .Values.domain }}
spec:
  namespace: {{ .Release.Namespace }}
---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: {{ .Values.domain }}
  namespace: {{ .Release.Namespace }}
spec:
  ref:
    name: {{ include "java-knative-demo.fullname" . }}
    kind: Service
    apiVersion: serving.knative.dev/v1
