apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "java-knative-demo.fullname" . }}
  labels:
    {{- include "java-knative-demo.labels" . | nindent 4 }}
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: "15s"  # Set a custom stable window
    spec:
      automountServiceAccountToken: false
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

