apiVersion: v1 
kind: Service
metadata:
  labels:
    name: {{ include "java-knative-demo.fullname" . }}-sm
  name: {{ include "java-knative-demo.fullname" . }}-sm
spec:
  ports:
  - name: app-metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    serving.knative.dev/service: {{ include "java-knative-demo.fullname" . }}
  type: ClusterIP