apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "java-knative-demo.fullname" . }}-sm
  labels:
    release: prometheus
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 10.4.1
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      name:  {{ include "java-knative-demo.fullname" . }}-sm
  endpoints:
  - port: app-metrics
    path: "/actuator/prometheus"
    scheme: http