# apiVersion: serving.knative.dev/v1beta1
# kind: DomainMapping
# metadata:
#   name: java-knative-demo.k8s.stein.solutions
#   namespace: demo-app-knative
# spec:
#   ref:
#     name: demo-app-knative
#     kind: Service
#     apiVersion: serving.knative.dev/v1
