apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-app-knative
  labels: 
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: "15s"  # Set a custom stable window
    spec:
      containers:
        - image: ghcr.io/stein-solutions/java-knative-demo:native-702f2e011f0cf35cac407e4c4f50bab0166d0bc6
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
