apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-knative-monitor
  labels:
    release: prometheus
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 10.4.1
spec:
  namespaceSelector:
    matchNames:
    - java-knative-demo
  selector:
    matchLabels:
      name:  demo-app-knative-service-monitor
  endpoints:
  - port: app-metrics
    path: "/actuator/prometheus"
    scheme: http