name: docker-image

on:
  push:
    paths-ignore:
      - 'kubernetes/**'      # Ignore changes in the 'docs' directory

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: dockerfile
          push: true
          tags: | 
            ghcr.io/${{ github.repository_owner }}/java-knative-demo:${{ github.sha }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: dockerfile.native
          push: true
          tags: | 
            ghcr.io/${{ github.repository_owner }}/java-knative-demo:native-${{ github.sha }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: dockerfile.nativelinked
          push: true
          tags: | 
            ghcr.io/${{ github.repository_owner }}/java-knative-demo:nativelinked-${{ github.sha }}
